Rizkyfransisca
helloproclub/gitiary pull request #35
Opened 2020-12-02 12:09 UTC by rizkyfransisca

2020-12-02 13:15 UTC, BlinfoldKing requested changes

2020-12-02 13:15 UTC, BlinfoldKing commented on list-nama.txt
> +
ini apaan

2020-12-02 14:31 UTC, rizkyfransisca commented
sudah bang

2020-12-04 06:42 UTC, BlinfoldKing approved these changes

2020-12-04 06:42 UTC, merged